/*
 * This file is generated by jOOQ.
 */
package com.codewithamit.jooq.tables.records;


import com.codewithamit.jooq.tables.Categories;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriesRecord extends UpdatableRecordImpl<CategoriesRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog-app-apis.categories.categoryId</code>.
     */
    public CategoriesRecord setCategoryid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.categories.categoryId</code>.
     */
    public Integer getCategoryid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog-app-apis.categories.description</code>.
     */
    public CategoriesRecord setDescription(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.categories.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blog-app-apis.categories.title</code>.
     */
    public CategoriesRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.categories.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Categories.CATEGORIES.CATEGORYID;
    }

    @Override
    public Field<String> field2() {
        return Categories.CATEGORIES.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return Categories.CATEGORIES.TITLE;
    }

    @Override
    public Integer component1() {
        return getCategoryid();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public Integer value1() {
        return getCategoryid();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public CategoriesRecord value1(Integer value) {
        setCategoryid(value);
        return this;
    }

    @Override
    public CategoriesRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CategoriesRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public CategoriesRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoriesRecord
     */
    public CategoriesRecord() {
        super(Categories.CATEGORIES);
    }

    /**
     * Create a detached, initialised CategoriesRecord
     */
    public CategoriesRecord(Integer categoryid, String description, String title) {
        super(Categories.CATEGORIES);

        setCategoryid(categoryid);
        setDescription(description);
        setTitle(title);
    }
}
