/*
 * This file is generated by jOOQ.
 */
package com.codewithamit.jooq.tables.records;


import com.codewithamit.jooq.tables.Comments;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommentsRecord extends UpdatableRecordImpl<CommentsRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog-app-apis.comments.id</code>.
     */
    public CommentsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.comments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog-app-apis.comments.content</code>.
     */
    public CommentsRecord setContent(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.comments.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blog-app-apis.comments.post_postId</code>.
     */
    public CommentsRecord setPostPostid(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.comments.post_postId</code>.
     */
    public Integer getPostPostid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Comments.COMMENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Comments.COMMENTS.CONTENT;
    }

    @Override
    public Field<Integer> field3() {
        return Comments.COMMENTS.POST_POSTID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getContent();
    }

    @Override
    public Integer component3() {
        return getPostPostid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getContent();
    }

    @Override
    public Integer value3() {
        return getPostPostid();
    }

    @Override
    public CommentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CommentsRecord value2(String value) {
        setContent(value);
        return this;
    }

    @Override
    public CommentsRecord value3(Integer value) {
        setPostPostid(value);
        return this;
    }

    @Override
    public CommentsRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommentsRecord
     */
    public CommentsRecord() {
        super(Comments.COMMENTS);
    }

    /**
     * Create a detached, initialised CommentsRecord
     */
    public CommentsRecord(Integer id, String content, Integer postPostid) {
        super(Comments.COMMENTS);

        setId(id);
        setContent(content);
        setPostPostid(postPostid);
    }
}
