/*
 * This file is generated by jOOQ.
 */
package com.codewithamit.jooq.tables.records;


import com.codewithamit.jooq.tables.UserRole;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleRecord extends TableRecordImpl<UserRoleRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>blog-app-apis.user_role.users</code>.
     */
    public UserRoleRecord setUsers(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.user_role.users</code>.
     */
    public Integer getUsers() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>blog-app-apis.user_role.role</code>.
     */
    public UserRoleRecord setRole(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.user_role.role</code>.
     */
    public Integer getRole() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserRole.USER_ROLE.USERS;
    }

    @Override
    public Field<Integer> field2() {
        return UserRole.USER_ROLE.ROLE;
    }

    @Override
    public Integer component1() {
        return getUsers();
    }

    @Override
    public Integer component2() {
        return getRole();
    }

    @Override
    public Integer value1() {
        return getUsers();
    }

    @Override
    public Integer value2() {
        return getRole();
    }

    @Override
    public UserRoleRecord value1(Integer value) {
        setUsers(value);
        return this;
    }

    @Override
    public UserRoleRecord value2(Integer value) {
        setRole(value);
        return this;
    }

    @Override
    public UserRoleRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRecord
     */
    public UserRoleRecord() {
        super(UserRole.USER_ROLE);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(Integer users, Integer role) {
        super(UserRole.USER_ROLE);

        setUsers(users);
        setRole(role);
    }
}
