/*
 * This file is generated by jOOQ.
 */
package com.codewithamit.jooq;


import com.codewithamit.jooq.tables.Categories;
import com.codewithamit.jooq.tables.Comments;
import com.codewithamit.jooq.tables.Posts;
import com.codewithamit.jooq.tables.Role;
import com.codewithamit.jooq.tables.UserRole;
import com.codewithamit.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlogAppApis extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>blog-app-apis</code>
     */
    public static final BlogAppApis BLOG_APP_APIS = new BlogAppApis();

    /**
     * The table <code>blog-app-apis.categories</code>.
     */
    public final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>blog-app-apis.comments</code>.
     */
    public final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>blog-app-apis.posts</code>.
     */
    public final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>blog-app-apis.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>blog-app-apis.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * The table <code>blog-app-apis.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private BlogAppApis() {
        super("blog-app-apis", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Categories.CATEGORIES,
            Comments.COMMENTS,
            Posts.POSTS,
            Role.ROLE,
            UserRole.USER_ROLE,
            Users.USERS);
    }
}
