/*
 * This file is generated by jOOQ.
 */
package com.codewithamit.jooq;


import com.codewithamit.jooq.tables.Categories;
import com.codewithamit.jooq.tables.Comments;
import com.codewithamit.jooq.tables.Posts;
import com.codewithamit.jooq.tables.Role;
import com.codewithamit.jooq.tables.UserRole;
import com.codewithamit.jooq.tables.Users;


/**
 * Convenience access to all tables in blog-app-apis.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>blog-app-apis.categories</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>blog-app-apis.comments</code>.
     */
    public static final Comments COMMENTS = Comments.COMMENTS;

    /**
     * The table <code>blog-app-apis.posts</code>.
     */
    public static final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>blog-app-apis.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>blog-app-apis.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * The table <code>blog-app-apis.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
