/*
 * This file is generated by jOOQ.
 */
package com.codewithamit.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categories implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer categoryid;
    private String  description;
    private String  title;

    public Categories() {}

    public Categories(Categories value) {
        this.categoryid = value.categoryid;
        this.description = value.description;
        this.title = value.title;
    }

    public Categories(
        Integer categoryid,
        String  description,
        String  title
    ) {
        this.categoryid = categoryid;
        this.description = description;
        this.title = title;
    }

    /**
     * Getter for <code>blog-app-apis.categories.categoryId</code>.
     */
    public Integer getCategoryid() {
        return this.categoryid;
    }

    /**
     * Setter for <code>blog-app-apis.categories.categoryId</code>.
     */
    public Categories setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.categories.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>blog-app-apis.categories.description</code>.
     */
    public Categories setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.categories.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>blog-app-apis.categories.title</code>.
     */
    public Categories setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Categories other = (Categories) obj;
        if (categoryid == null) {
            if (other.categoryid != null)
                return false;
        }
        else if (!categoryid.equals(other.categoryid))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        }
        else if (!title.equals(other.title))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.categoryid == null) ? 0 : this.categoryid.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Categories (");

        sb.append(categoryid);
        sb.append(", ").append(description);
        sb.append(", ").append(title);

        sb.append(")");
        return sb.toString();
    }
}
