/*
 * This file is generated by jOOQ.
 */
package com.codewithamit.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comments implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  content;
    private Integer postPostid;

    public Comments() {}

    public Comments(Comments value) {
        this.id = value.id;
        this.content = value.content;
        this.postPostid = value.postPostid;
    }

    public Comments(
        Integer id,
        String  content,
        Integer postPostid
    ) {
        this.id = id;
        this.content = content;
        this.postPostid = postPostid;
    }

    /**
     * Getter for <code>blog-app-apis.comments.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>blog-app-apis.comments.id</code>.
     */
    public Comments setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.comments.content</code>.
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>blog-app-apis.comments.content</code>.
     */
    public Comments setContent(String content) {
        this.content = content;
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.comments.post_postId</code>.
     */
    public Integer getPostPostid() {
        return this.postPostid;
    }

    /**
     * Setter for <code>blog-app-apis.comments.post_postId</code>.
     */
    public Comments setPostPostid(Integer postPostid) {
        this.postPostid = postPostid;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Comments other = (Comments) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (content == null) {
            if (other.content != null)
                return false;
        }
        else if (!content.equals(other.content))
            return false;
        if (postPostid == null) {
            if (other.postPostid != null)
                return false;
        }
        else if (!postPostid.equals(other.postPostid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.postPostid == null) ? 0 : this.postPostid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comments (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(postPostid);

        sb.append(")");
        return sb.toString();
    }
}
