/*
 * This file is generated by jOOQ.
 */
package com.codewithamit.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRole implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer users;
    private Integer role;

    public UserRole() {}

    public UserRole(UserRole value) {
        this.users = value.users;
        this.role = value.role;
    }

    public UserRole(
        Integer users,
        Integer role
    ) {
        this.users = users;
        this.role = role;
    }

    /**
     * Getter for <code>blog-app-apis.user_role.users</code>.
     */
    public Integer getUsers() {
        return this.users;
    }

    /**
     * Setter for <code>blog-app-apis.user_role.users</code>.
     */
    public UserRole setUsers(Integer users) {
        this.users = users;
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.user_role.role</code>.
     */
    public Integer getRole() {
        return this.role;
    }

    /**
     * Setter for <code>blog-app-apis.user_role.role</code>.
     */
    public UserRole setRole(Integer role) {
        this.role = role;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserRole other = (UserRole) obj;
        if (users == null) {
            if (other.users != null)
                return false;
        }
        else if (!users.equals(other.users))
            return false;
        if (role == null) {
            if (other.role != null)
                return false;
        }
        else if (!role.equals(other.role))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.users == null) ? 0 : this.users.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRole (");

        sb.append(users);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
