/*
 * This file is generated by jOOQ.
 */
package com.codewithamit.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  about;
    private String  email;
    private String  userName;
    private String  password;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.about = value.about;
        this.email = value.email;
        this.userName = value.userName;
        this.password = value.password;
    }

    public Users(
        Integer id,
        String  about,
        String  email,
        String  userName,
        String  password
    ) {
        this.id = id;
        this.about = about;
        this.email = email;
        this.userName = userName;
        this.password = password;
    }

    /**
     * Getter for <code>blog-app-apis.users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>blog-app-apis.users.id</code>.
     */
    public Users setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.users.about</code>.
     */
    public String getAbout() {
        return this.about;
    }

    /**
     * Setter for <code>blog-app-apis.users.about</code>.
     */
    public Users setAbout(String about) {
        this.about = about;
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>blog-app-apis.users.email</code>.
     */
    public Users setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.users.user_name</code>.
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>blog-app-apis.users.user_name</code>.
     */
    public Users setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>blog-app-apis.users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>blog-app-apis.users.password</code>.
     */
    public Users setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (about == null) {
            if (other.about != null)
                return false;
        }
        else if (!about.equals(other.about))
            return false;
        if (email == null) {
            if (other.email != null)
                return false;
        }
        else if (!email.equals(other.email))
            return false;
        if (userName == null) {
            if (other.userName != null)
                return false;
        }
        else if (!userName.equals(other.userName))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.about == null) ? 0 : this.about.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.userName == null) ? 0 : this.userName.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(about);
        sb.append(", ").append(email);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
